### ISSUE TITLE
Is the project still maintained?

### ISSUE THREAD

**Issue by mytototo** [api-stack/api-stack#47]
Hi!

I just tried the repo and most of the APIs don't respect the Swagger spec. Impossible to parse them with the Swagger UI.

Do you plan to fix them? Or the project is not maintained anymore?

Thanks.

**Comment by kinlane** [comment]
Hey there...thanks for dropping me a line. 

The repos have gone dormant because I took the spring and summer off to deal with a family issue. 

Secondarily not all my OpenAPI specs will be complete. My goal is always to make them as complete as possible, which you can see with a handful - http://theapistack.com/certifying/.  My goal is to define 1) paths 2) params 3) auth 4) underlying data schemas -- but it is a lot of work and takes time, as its usually unpaid work for me.

My goal is to make discoverable, and secondarily usable.....I'll be publishing an updated list ASAP, probably in the next couple of weeks. 

Thanks for your interest!...feel free to submit any you have more complete -- could use the help. ;-)
